import { Inter, Roboto } from "next/font/google"
import "./globals.css"
import Navbar from "@/components/Navbar"
// import Navbar from "@/components/Navbar"

const inter = Inter({ subsets: ["latin"] })
const roboto = Roboto({weight : ['300', '500', '700'] ,subsets: ["latin"] })

export const metadata = {
  title: {
    default: "Next Hero",
    template: "%s | Next Hero"
  },
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navbar></Navbar>
        {/* This is about */}
        <div className="">{children}</div>
        <footer className="bg-blue-400">This is my footer</footer>
      </body>
    </html>
  )
}
